# Generated by Django 5.0.4 on 2024-04-17 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(max_length=100)),
                ('Pin', models.IntegerField()),
                ('Date', models.DateField()),
                ('Signin', models.TimeField()),
                ('Signout', models.TimeField()),
                ('Workinghour', models.IntegerField()),
            ],
            options={
                'db_table': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='Celebration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.TextField()),
            ],
            options={
                'db_table': 'celebration',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavetype', models.CharField(choices=[('sick leave', 'sick leave'), ('casual leave', 'casual leave'), ('maternity leave', 'maternity leave'), ('paternity leave', 'paternity leave'), ('annual leave', 'annual leave')], max_length=100)),
                ('notes', models.CharField(max_length=100)),
                ('dates', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='pending', max_length=10)),
            ],
            options={
                'db_table': 'leave',
            },
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'relationtype',
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofbirth', models.DateField()),
                ('dateofjoining', models.DateField()),
                ('department', models.CharField(choices=[('administration', 'administration'), ('Research', 'Research'), ('sales', 'sales'), ('marketing', 'markrting')], max_length=100)),
                ('address', models.TextField()),
                ('emergencycontactno', models.CharField(max_length=100)),
                ('lastappraisaldate', models.DateField()),
            ],
            options={
                'db_table': 'userdetail',
            },
        ),
        migrations.CreateModel(
            name='UserRelative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotactnumber', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'userrelative',
            },
        ),
        migrations.CreateModel(
            name='CelebrationParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('celebration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.celebration')),
            ],
            options={
                'db_table': 'celebrationparticipants',
            },
        ),
    ]
